---
- hosts: teamcity
  vars:
    teamcity_user: teamcity
    teamcity_user_home: "/home/{{teamcity_user}}"
    version: 8.0.3
    download_path: "{{teamcity_user_home}}/TeamCity-{{version}}.tar.gz"
    install_dir: "{{teamcity_user_home}}"
    install_path: "{{install_dir}}/TeamCity"
    data_path: "{{teamcity_user_home}}/TeamCityData"
  tasks:
    - name: update cache
      apt: update_cache=yes
    - name: install curl
      apt: pkg=curl

    - name: install java
      apt: pkg=openjdk-7-jre

    - name: create user running teamcity
      user: name={{teamcity_user}} home=$teamcity_user_home comment="User running TeamCity"

    - name: download teamcity
      get_url: url=http://download.jetbrains.com/teamcity/TeamCity-{{version}}.tar.gz dest=$download_path

    - name: unpack archive
      command: tar -xvzf "{{download_path}}" --directory "{{install_dir}}" creates=$install_path

    - name: set install directory owner
      file: path=$install_path owner=$teamcity_user group=$teamcity_user recurse=yes state=directory

    - name: copy teamcity startup script
      template: src=./templates/teamcity_service_script.sh.j2 dest=/etc/init.d/teamcity mode=755

    - name: install teamcity as a service
      service: name=teamcity enabled=yes state=started

    # Generate a ssh key
    - name: create ssh directory
      file: path="{{teamcity_user_home}}/.ssh" state=directory
    - name: create ssh key
      command: ssh-keygen -t rsa -q -f "{{teamcity_user_home}}/.ssh/id_rsa" -N '' creates="{{teamcity_user_home}}/.ssh/id_rsa.pub"
    - name: change permissions on ssh directory
      file: path="{{teamcity_user_home}}/.ssh" owner=$teamcity_user group=$teamcity_user recurse=yes state=directory mode=700







